# change the followings to match your Github username and repo name
baseurl: "/landing" # the name of your github repo
url: "https://noxfs.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Nox"
description: Nox Film Studio

# color theme for links
theme-color: stone # indigo|yellow|pink|green|stone|

# homepage information
author: Nox
author-bio: false  # change to false to hide
author-image: logo.svg  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: false

nav-menu:
- text: About
  permalink: about
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: false
facebook: false
instagram: false
github: false
linkedin: false
medium: false
google-scholar: false
email: false

# footer information
footer-msg: "Coming Soon"
footer-msg-link: https://noxfs.com

# google analytics
google-analytics: false

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
